### ISSUE TITLE
Endpoints options are not populated

### ISSUE THREAD

**Issue by moleman** [stefanolsen/episerver-events#1]
Hi!

Thanks for the effort creating this provider. We are currently looking into using it when upgrading to Optimizely 12 but we found some issues when trying it out.

When using the `UdpUnicastEventProviderOptions` configuration section in appSettings.json, the `Endpoints` list is always empty even if you specify items. A solution is to, instead of initializing the endpoints property with `Array.Empty<UdpEndpoint>()`, change it to `new List<UdpEndpoint>()`.

I can create a PR for this.

**Comment by stefanolsen** [comment]
Happy to know you find it useful, @moleman. Thanks for your suggestions and your PR.

I will look into packing and pushing to the Optimizely Nuget feed.
