### ISSUE TITLE
Hostnames are not supported in endpoints configuration

### ISSUE THREAD

**Issue by moleman** [stefanolsen/episerver-events#2]
The README doc mention that it is possible to use a hostname as an endpoint but it will fail because the code expects it to be an IP address.

```
        "UdpUnicastEventProvider": {
            "BindHost": "0.0.0.0",
            "Port: 6000,
            "Endpoints": [
                { "Host": "server2.local", "Port": 6000 },
                { "Host": "server3.local", "Port": 6000 }
            ]
        }
```

See `IPAddress.Parse` at 
https://github.com/stefanolsen/episerver-events/blob/main/src/EPiServer.Events.Sockets/UdpUnicastEventProvider.cs#L25

**Comment by stefanolsen** [comment]
@moleman: This is now fixed and merged.

Thanks for reporting.
