### ISSUE TITLE
Publish a nuget package

### ISSUE THREAD

**Issue by moleman** [stefanolsen/episerver-events#3]
It would be great if this provider would be published as a nuget package to https://www.nuget.org/packages. 
This would make it easier for developers to use the provider.

**Comment by stefanolsen** [comment]
@moleman: Just published it to the Optimizely NuGet feed. Waiting for the review approval.

**Comment by stefanolsen** [comment]
@moleman: Now it is finally on the [NuGet feed](https://nuget.optimizely.com/package/?id=StefanOlsen.Optimizely.Events.Sockets).

Are you able to test it out?

**Comment by moleman** [comment]
@stefanolsen Nice! Thanks.

Unfortunately I'm not able to test at the moment because I'm not currently working with EPiServer 12 but I don't see why it shouldn't work.
